### ISSUE TITLE
Questions about Training YOLOv8

### ISSUE THREAD

**Issue by namho-96** [WildChlamydia/MiVOLO#11]
Thanks for the great research.
I want to know what datasets were used to train your YOLOv8?
I couldn't find any explanation of that in your paper.
thx!

**Comment by WildChlamydia** [comment]
Hello! Thank you for your kind words. This detector has been trained on specialized data within this visual domain. Unfortunately, the data is not available for open-source use.

**Comment by namho-96** [comment]
Thank you for your response.
I'll be looking forward to seeing the dataset released later.
