### ISSUE TITLE
The Lagenda dataset should have a very good effect on race recognition

### ISSUE THREAD

**Issue by zhongtao93** [WildChlamydia/MiVOLO#12]
Hi, the natural thought is that human body should increase the precision of race recognition, since that body can remove the impact of makeup. Have you annoted the dataaset for race recognition?

**Comment by WildChlamydia** [comment]
Hello! No, we have not . This task falls outside the scope of our goals. However, any attributes can be integrated in a similar manner: as additional outputs, and should work quite well.
