### ISSUE TITLE
Lagenda Dataset Download

### ISSUE THREAD

**Issue by aylinSyntonym** [WildChlamydia/MiVOLO#13]
I couldn't able to download the Lagenda Dataset due to the large big file, and I try to download the dataset again I am getting following error from Google Drive  "Sorry, you can't view or download this file at this time. Too many users have viewed or downloaded this file recently. Please try accessing the file again later. If the file you are trying to access is particularly large or is shared with many people, it may take up to 24 hours to be able to view or download the file. If you still can't access a file after 24 hours, contact your domain administrator." constantly. Is there anyway to download the dataset?

**Comment by WildChlamydia** [comment]
Could you please attempt this a bit later? It seems that Google has limited the number of downloads. At the moment, I'm unable to mirror the data due to its heavy size.
