### ISSUE TITLE
The age estimation result

### ISSUE THREAD

**Issue by tungedng2710** [WildChlamydia/MiVOLO#16]
I've used your model to predict my dataset (each image has exactly one face). After calling ```detected_objects.ages```,  I got the list of 2-3 elements and one of them is None. What is the true result? I also set both arguments ```use_persons``` and ```disable_faces``` as ```False``` when calling MiVOLO class.

**Comment by sweetdream779** [comment]
Hello.

`detected_objects.ages` list contains age predictions for each found object (face or person).  I.e. `detected_objects.ages[i]` is the prediction for `detected_objects.yolo_results.boxes[i]` bbox. 

When you set `use_persons=False`, you use **only faces** for age prediction. This is the cause why person's bboxes do no have ages (age of object with 'person' category set to None).
