### ISSUE TITLE
Training and Evaluating on other datasets

### ISSUE THREAD

**Issue by jordanhart** [WildChlamydia/MiVOLO#2]
Hi! Awesome work. Would it be possible to get instructions and/or code for both training on and evaluating for other well known datasets, in my case PETA, PA-100K, and RAP. 

Thank you!

**Comment by sweetdream779** [comment]
Hello. Thank you for your feedback! 

For training, we used the timm framework, and you can find the training scripts in their [repository](https://github.com/huggingface/pytorch-image-models/tree/v0.8.13dev0) 

To validate our model on a new dataset, you need to convert your dataset to our CSV format, the description of which you can find here: https://wildchlamydia.github.io/lagenda/. You can download annotations for one of the datasets we use as examples.

Examples of conversion scripts for the fairface dataset (with face and body detection) and the adience dataset (with face detection only) can be found in the `tools/prepare_fairface.py` and `tools/prepare_adience.py`, respectively.

Don't forget to add the name of your dataset to the `DATASET_CLASS_MAP` dictionary [here](https://github.com/WildChlamydia/MiVOLO/blob/main/mivolo/data/dataset/__init__.py#L10) and to the valid values for the `--dataset_name` argument [here](https://github.com/WildChlamydia/MiVOLO/blob/main/eval_pretrained.py#L27).

**Comment by jordanhart** [comment]
Thank you!
