### ISSUE TITLE
inconsistent results 

### ISSUE THREAD

**Issue by SoaresMuquissi** [WildChlamydia/MiVOLO#21]
Thank you for the cool solution.

Do you know why the result from https://huggingface.co/spaces/iitolstykh/age_gender_estimation_demo is different from local  one ? i clone your repo and i used model_imdb_cross_person_4.22_99.46.pth.tar and yolov8x_person_face.pt 

but i got many false positives

**Comment by sweetdream779** [comment]
Hello, our demo uses proprietary model, it is more accurate than our open-source model.
