### ISSUE TITLE
I found the evaluation part, but I can't find the train part.

### ISSUE THREAD

**Issue by ahn19** [WildChlamydia/MiVOLO#29]
There is no train part in this repository, am I right?

**Comment by parissalmu** [comment]
I am also looking for the train module as well, but it seems like it's not available in the repo

**Comment by parissalmu** [comment]
If you look into the closed issues, the authors have mentioned that they cannot release the training code

**Comment by WildChlamydia** [comment]
Hello. At the moment, we are not considering publishing the train code. However, we are always ready to advise you if you encounter problems while writing your own train loop.
