### ISSUE TITLE
Finetune with timm framework

### ISSUE THREAD

**Issue by thanhtung0512** [WildChlamydia/MiVOLO#30]
I want to finetune your model on my own dataset. I got ur answer from closed issue that we can use timm framework to do that task. But i can't find ur model from timm list models. How to do that with timm. Tks so much

**Comment by WildChlamydia** [comment]
"Hello! There is indeed no model on Hugging Face yet. We talked about how we built the training code ourselves based on the training code from timm, simply modifying the original VOLO's classification to regression.
