### ISSUE TITLE
Run only age-gender predictions with custom face-crops

### ISSUE THREAD

**Issue by PogChamper** [WildChlamydia/MiVOLO#34]
Hello!
Is it possible to put custom crops into age-gender prediction model, excluding face detection part?
Thanks in advance for any help.

**Comment by WildChlamydia** [comment]
Hello.
You can use inference method directly: https://github.com/WildChlamydia/MiVOLO/blob/main/mivolo/model/mi_volo.py#L143

**Comment by sweetdream779** [comment]
See also this response: https://github.com/WildChlamydia/MiVOLO/issues/6#issuecomment-1650360596
