### ISSUE TITLE
Age detection without face detection

### ISSUE THREAD

**Issue by PolarRobin** [WildChlamydia/MiVOLO#35]
Hi,
is there an easy way to disable the face detection in images? 
Reason: I already have cropped images of faces and want to only execute age estimation on them. But I have a hard time creating an empty PersonAndFaceResult in the Predictor class and populate it with my image and a bounding box of the face that spreads over the whole image.

**Comment by sweetdream779** [comment]
You can adapt the script from this answer https://github.com/WildChlamydia/MiVOLO/issues/26#issuecomment-1895406094
