### ISSUE TITLE
how can I get mivolov2_d1_384x384 🙂

### ISSUE THREAD

**Issue by liuzhougithub** [WildChlamydia/MiVOLO#41]
I noticed that the mivolov2_d1_384x384 model isn't available publicly yet. I'm very interested in testing it out and seeing if there's any way I can help improve it. Is there any chance I could get access to it?

Thanks a lot for your time and help!

**Comment by WildChlamydia** [comment]
The commercial model is currently unavailable. However, you can access it through our Telegram bot. It's easy, free, and fast:
https://t.me/anyagebot
