### ISSUE TITLE
Question of release the training source code 

### ISSUE THREAD

**Issue by GWwangshuo** [WildChlamydia/MiVOLO#7]
Thanks for your awesome work. Could you please release the training source code? Thanks a lot.

**Comment by WildChlamydia** [comment]
We apologize, but for now, it's not possible due to trade secrets and other issues. Reproducing the training procedure with the timm module and with our model is not difficult; it is quite similar to simple classification.

**Comment by PascalIversen** [comment]
Could you post a simple example training loop minus the trade secrets?

**Comment by n0kovo** [comment]
Could you give a super high-level explanation of how one could attempt to reproduce the training procedure with TIMM?

**Comment by robinjacobroy** [comment]
I’ve implemented an unofficial training script that may help others.
https://github.com/robinjacobroy/MiVOLO/blob/main/train.py
